"""empty message

Revision ID: 459ebdba150b
Revises: 
Create Date: 2023-11-01 21:40:36.463484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '459ebdba150b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('token', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('password_reset', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_reset_email'), ['email'], unique=False)

    op.create_table('preference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rental_type', sa.String(length=50), nullable=False),
    sa.Column('pets_policy', sa.String(length=50), nullable=False),
    sa.Column('smoking_policy', sa.String(length=50), nullable=False),
    sa.Column('gender_policy', sa.String(length=50), nullable=False),
    sa.Column('sleep_policy', sa.String(length=50), nullable=False),
    sa.Column('term_policy', sa.String(length=50), nullable=False),
    sa.Column('additional_requirements', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=150), nullable=False),
    sa.Column('lastname', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=150), nullable=False),
    sa.Column('user_type', sa.Enum('user', 'landlord', 'admin'), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('preference')
    with op.batch_alter_table('password_reset', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_reset_email'))

    op.drop_table('password_reset')
    # ### end Alembic commands ###
