"""Create Preference_ll table

Revision ID: d68108c11241
Revises: 0c869e1fa48f
Create Date: 2024-01-06 17:14:13.682615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd68108c11241'
down_revision = '0c869e1fa48f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('preference_ll',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rental_type', sa.String(length=50), nullable=False),
    sa.Column('pets_policy', sa.String(length=50), nullable=False),
    sa.Column('smoking_policy', sa.String(length=50), nullable=False),
    sa.Column('gender_policy', sa.String(length=50), nullable=False),
    sa.Column('sleep_policy', sa.String(length=50), nullable=False),
    sa.Column('term_policy', sa.String(length=50), nullable=False),
    sa.Column('additional_requirements', sa.String(length=200), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('preference_ll')
    # ### end Alembic commands ###
