"""empty message

Revision ID: d75061425d24
Revises: 383651ff2dd0
Create Date: 2024-01-06 16:43:19.054153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd75061425d24'
down_revision = '383651ff2dd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('preference_ll',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rental_type', sa.String(length=50), nullable=False),
    sa.Column('nationality_type', sa.String(length=50), nullable=False),
    sa.Column('term_policy', sa.String(length=50), nullable=False),
    sa.Column('additional_requirements', sa.String(length=200), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('preference_ll')
    # ### end Alembic commands ###
